<?php

namespace Drupal\content_changes_notify\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class SettingsForm extends ConfigFormBase {
  protected function getEditableConfigNames() {
    // TODO: Implement getEditableConfigNames() method.
    return [
      'content_changes_notify.settings'
    ];
  }
  public function getFormId() {
    return 'content_changes_notify_admin_settings';
  }

  public function buildForm(array $form, FormStateInterface $form_state)
  {
    $form['test'] = [
      '#type' => 'textfield',
      '#default_value' => 'test',
      '#title' => 'Test',
    ];

    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }
}
