<?php

/**
 * @file
 * Contains content_changes_notify.module.
 */


/**
 * TODO: eliminare a fine lavorazione, prima del push.
 * ISSUE Desc:
 * ciao @ninomarrazzo
 * il task consiste nell'invio di un'email a un set (configurabile) di indirizzi predefiniti nel momento in cui viene modificato un certo tipo di contenuto (configurabile).
 * di default è "page". il messaggio conterrà l'indirizzo e il titolo del contenuto + lo stato del workflow (es. bozza, in pubblicazione, etc.)
 * @danielaiozzo è corretto ? o le email devono essere inviate solo per alcuni cambi nel workflow ? e/o solo quando la modifica avviene da utenti di un particolare ruolo ?
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function content_changes_notify_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the content_changes_notify module.
    case 'help.page.content_changes_notify':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Implements the possibiliy to choose on which content&#039;s changes which one (configurable)  users will be notified through mail') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function content_changes_notify_theme() {
  return [
    'content_changes_notify' => [
      'render element' => 'children',
    ],
  ];
}
