<?php

/**
 * @file
 * Contains agid_base.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Menu\MenuLinkInterface;
use Drupal\menu_link_content\Plugin\Menu\MenuLinkContent;

/**
 * Implements hook_theme().
 */
function agid_base_theme($existing, $type, $theme, $path) {
  $theme = [];
  $theme['agid_base_share_links'] = [
    'template' => 'agid-base-share-links',
    'path' => $path . '/templates',
    'variables' => [
      'entity_url' => NULL,
      'entity_title' => NULL,
      'entity_summary' => NULL,
    ],
  ];
  return $theme;
}

/**
 * Implements hook_field_widget_form_alter().
 */
function agid_base_field_widget_form_alter(&$element, FormStateInterface &$form_state, $context) {
  /** @var \Drupal\Core\Field\FieldItemListInterface $items */
  $items = $context['items'];
  if ($items->getName() != 'field_iconfont') {
    return;
  }

  $element['value']['#type'] = 'select';
  $element['value']['#options'] = agid_base_get_icon_options();
  unset($element['value']['#size']);
}

/**
 * Get a list of icon options.
 *
 * @return array
 *   An array containing the class name as key and the icon name as value.
 */
function agid_base_get_icon_options() {
  $options = [];
  $dir = drupal_get_path('theme', 'italiagov') . '/build/src/icons/icons/img/SVG';
  foreach (file_scan_directory($dir, '/\.svg$/', []) as $icon) {
    $options['Icon-' . $icon->name] = $icon->name;
  }

  return ['' => t('-- Select -- ')] + $options;
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function agid_base_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  if ($route_match->getRouteName() == 'entity.webform.canonical') {
    $links = $breadcrumb->getLinks();
    $breadcrumb = new Breadcrumb();
    $breadcrumb->setLinks([end($links)]);
  }
}

/**
 * Implements hook_editor_js_settings_alter().
 * based on: https://drupal.stackexchange.com/questions/193521/how-do-i-modify-the-formats-dropdown-in-ckeditor
 */
function agid_base_editor_js_settings_alter(array &$settings) {
  // Get current user
  $userCurrent = \Drupal::currentUser();
  // Load user's object
  $userObject  = \Drupal\user\Entity\User::load($userCurrent->id());
  // Get all user's roles
  $roles = $userObject->getRoles();
  // Check if has only author role and then...
  if ((in_array('author', $roles) || in_array('publisher', $roles)) && !in_array('administrator', $roles)) {
    // ... Set only p, h1 and h2 text formats.
    $settings['editor']['formats']['filtered_text']['editorSettings']['format_tags'] = 'p;h1;h2';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function agid_base_preprocess_menu(&$variables) {
  if ($variables['menu_name'] == 'main') {
    // Get current language
    $language = Drupal::languageManager()->getCurrentLanguage()->getId();
    // Check language, foreach item...
    foreach ($variables['items'] as $key => &$item) {
      // Load entity by UUID
      $menuLinkEntity = agid_base_load_entity_by_link($item['original_link']);
      if ($menuLinkEntity !== NULL) {
        $languages = $menuLinkEntity->getTranslationLanguages();
        // Check if is translated...
        if (!array_key_exists($language, $languages)) {
          unset($variables['items'][$key]);
        } else {
          // Check if has below and search for untranslated children
          if (count($variables['items'][$key]['below']) > 0) {
            foreach ($variables['items'][$key]['below'] as $keyBelow => $itemBelow) {
              $menuLinkEntityBelow = agid_base_load_entity_by_link($itemBelow['original_link']);
              if ($menuLinkEntityBelow !== NULL) {
                $languagesBelow = $menuLinkEntityBelow->getTranslationLanguages();
                if (!array_key_exists($language, $languagesBelow)) {
                  unset($variables['items'][$key]['below'][$keyBelow]);
                }
              }
            }
          }
        }
      }
    }
  }
}

/*
 * Loads menu item entity by its UUID
 */
function agid_base_load_entity_by_link(MenuLinkInterface $menuLinkContentPlugin) {
  $entity = NULL;

  if ($menuLinkContentPlugin instanceof MenuLinkContent) {
    list($entity_type, $uuid) = explode(':', $menuLinkContentPlugin->getPluginId(), 2);
    $entity = \Drupal::entityManager()->loadEntityByUuid($entity_type, $uuid);
  }
  return $entity;
}